---
title: "Baseball Project Code"
author: "Emma Godfrey"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pitches <- read.csv("~/Downloads/pitches.csv")
```

```{r}
library("tidyverse")
library("tune")
library("randomForest")
library("ROCR")
library("ROSE")
library("ggplot2")
library("reshape2")
library("scatterplot3d")
library("e1071")
library("xgboost")
library("caret")
library("ggfortify")
library("Ckmeans.1d.dp")
```

```{r}
# only consider events where the batter swings at the ball
pitches <- pitches %>% 
  filter(is.na(pitches) == FALSE) %>% 
  filter(code %in% c("L", "T", "F", "X", "D", "E", "S", "W", "M")) %>% 
  mutate(swing.miss = ifelse(code == "S" & type == "S" | code == "W" & type == "S" | code == "M" & type == "S", 1, 0))

# change it to a factor variable 
pitches$swing.miss <- as.factor(pitches$swing.miss)
pitches$type <- as.factor(pitches$type)
```

```{r}
# Cool 3D graphs
# for reproduciblity 
set.seed(100)
pitches.samp <- pitches[sample(nrow(pitches),700, replace = FALSE),]

colors <- c("red", "blue", alpha = 0.2)
colors <- colors[as.numeric(pitches.samp$swing.miss)]
s3d <- scatterplot3d(x=pitches.samp$pfx_x, y=pitches.samp$pfx_z, z= pitches.samp$end_speed, pch= 10, color = colors, main = "Pitch speed and change in trajectory to predict swing contact", xlab = "Change in horizontal trajectory (pfx_x)", zlab = "End speed", ylab = "Change in vertical trajectory (pfx_z)")
legend(s3d$xyz.convert(10, -10,60), col= c("red", "blue"), bg="white", lty=c(1,1), lwd=2, yjust=0, legend = c("Swing & contact", "Swing & no contact"), cex = 0.5)

```


```{r}
# More cool 3D graphs 
p <- ggplot(data = pitches.samp, mapping = aes(x=pfx_x, y=pfx_z, color = swing.miss)) + 
  geom_point(aes(alpha = end_speed)) + labs(x="Change in Horizontal Trajectory (pfx_x)", y="Change in Vertical Trajectory (pfx_z)", color = "Contact (0=yes, 1 =no)", alpha = "End Speed", title = "Will the batter make contact?", subtitle = "the change in horizontal/vertical trajectory and end speed of pitch affecting contact likelihood") + 
  theme_minimal() +theme(plot.title = element_text(face = "bold"))
```


Dissecting likelihood of contact by type of pitch. 
```{r}
# only consider changeup, curveball, slider, and fastballs 
pitches3 <- pitches %>% 
  filter(pitch_type == "CH" | pitch_type == "CU" | pitch_type == "SL" | pitch_type == "FF"| pitch_type == "FT")

ggplot(data=pitches3, aes(x=pitch_type, fill = swing.miss)) + 
  geom_bar() + 
  labs(x="Pitch Type", y="Contact vs. No Contact Count", fill = "Ball Contact (0=yes, 1 =no)", title = "Pitch Type and Contact") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))
```

```{r}
# visualizing ball movement by pitch type

ggplot(data = pitches.samp, aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir))

pitches.samp.fastball <- pitches %>% 
  filter(pitch_type == "FF" | pitch_type == "FT")

pitches.samp.curveball <- pitches %>% 
  filter(pitch_type == "CU")

pitches.samp.change <- pitches %>% 
  filter(pitch_type == "CH")

fast <- ggplot(data = pitches.samp.fastball[1:500,], aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do fastball spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)")+ 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

curve <- ggplot(data = pitches.samp.curveball[1:500,], aes(color=swing.miss)) +
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do curveball spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

change <- ggplot(data = pitches.samp.change[1:500,], aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do changeup spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

ggplot(data=pitches3, aes(x=zone, fill = swing.miss)) + 
  geom_bar() + 
  labs(x="Zone", y="Contact vs. No Contact Count", fill = "Ball Contact (0=yes, 1=no)", title = "Zone and Contact") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")
```

```{r}
# making the dataset muuuuch smaller so I can create some models 
set.seed(100)
pitches5 <- pitches[sample(nrow(pitches), 0.05*nrow(pitches), replace = FALSE),]
pitches5$type <- as.factor(pitches5$type)
```


```{r training and testing}
# feature reduced training and testing datasets 
train.samp <- sample(nrow(pitches5), 0.7*nrow(pitches5), replace= FALSE)
training <- pitches5[train.samp,-c(28, 29,31,32,33,34,35,36,37,38,39,40)]
testing <- pitches5[-train.samp,-c(28, 29,31,32,33,34,35,36,37,38,39,40)]

```

```{r}
# up-sampling
training.balanced <- ovun.sample(swing.miss~., data = training, method = "over")$data

# balanced dataset 
table(training.balanced$swing.miss)

# random sample to build models on 
model.samp <- sample(nrow(training.balanced), 0.5*nrow(training.balanced), replace=FALSE)
training.build.model <- training.balanced[model.samp,]

# cleaning training and testing data 
training.build.model$zone <- as.factor(training.build.model$zone)
training.build.model$pitch_type <- as.factor(training.build.model$pitch_type)
training.build.model$nasty <- as.numeric(training.build.model$nasty)

testing$zone <- as.factor(testing$zone)
testing$pitch_type <- as.factor(testing$pitch_type)
testing$nasty <- as.numeric(testing$nasty)
levels(training.build.model$pitch_type)

# take out a level to make training and testing match on level numbers 
training.build.model <- droplevels(training.build.model[!training.build.model$pitch_type == 'FA',])
```

```{r}
### RANDOM FOREST 

# tune mtry -- # of variables randomly chosen to split on at each tree
# takes about 5 minutes to tune 
# mtry optimal = 10 
rf.tune <- tuneRF(training.build.model[,-29], training.build.model[,29], ntreeTry = 50, verbose=TRUE)

rf1 <- randomForest(swing.miss ~ ., data = trainig.build.model, ntree=500, mtry=10, do.trace = 100)

# testing data predictions 
predictions <- predict(rf1, newdata = testing[,-29],type="prob") 

pred <- prediction(predictions[,2], testing[,29])
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf, col="blue", main= "Random Forest Performance (AUROC = 0.746)")

# AUC -- 0.745
auc.perf <- performance(pred, measure = "auc")
print(auc.perf@y.values)

# importance plot 
var.imp1 <- data.frame(importance(rf1, type=2))
var.imp1$Variables <- row.names(var.imp1)
varimp1 <- var.imp1[order(var.imp1$MeanDecreaseGini,decreasing = T),]
par(mar=c(10,5,1,1)) 
giniplot <- barplot(t(varimp1[-2]/sum(varimp1[-2])),las=2,
                     cex.names=1,
                    main="Gini Impurity Index Plot")

# variable importance plot -- simple 
varImpPlot(rf1, n.var =10, main ="Random Forest Variable Importance")

```


```{r}

### Support Vector Machine 
# too computationally intensive for my computer -- never finished
tune_out <- tune.svm(swing.miss ~., data = training.build.model, gamma = 2^(-2:2), cost = 2^(-2:2))

# rbf kernel 
svmfit1 <- svm(swing.miss~., data = training.build.model, type = 'C-classification', verbose=TRUE)

# linear kernel -- takes about 10 mins to run 
svmfit <- svm(swing.miss ~., data = training.build.model, kernel="linear",cost=1)

prediction.svm <- predict(svmfit, newdata = testing, type = "decision")
prediction.svm.test <- prediction(as.numeric(prediction.svm), testing$swing.miss)
perf.svm <- performance(prediction.svm.test, measure = "tpr", x.measure = "fpr")
plot(perf.svm, col="blue", main= "SVM Performance (AUROC = 0.697)")

# AUC -- 0.745
auc.perf.svm <- performance(prediction.svm.test, measure = "auc")
print(auc.perf.svm@y.values)


# test svm 
svm.test <- predict(svmfit, training.build.model[,29])

# principal decomp attempt -- do more later!
princomp <- prcomp(training.build.model[,-c(27,28,29)], scale=TRUE)
autoplot(princomp, data = training.build.model, colour = "swing.miss")
pca.training <-cbind(princomp$x[,1:4])
pca.training <- cbind(pca.training,training.build.model$swing.miss)
```

```{r XBG}

# data cleaning for XGBoost
training.build.model.labels <- training.build.model[,29]
training.build.model.features <- training.build.model[,-29]
dtrain <- xgb.DMatrix(data = as.matrix(training.build.model[,-c(27,28,29)]), label= as.matrix(training.build.model$swing.miss))
dtest <- xgb.DMatrix(data = as.matrix(testing[,-c(27,28,29)]), label= as.matrix(testing$swing.miss))

# fit an XGBoost
xgboost.fit <- xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nrounds = 200, objective = "binary:logistic")

# test the model on test data 
pred.xgb <- predict(xgboost.fit, dtest)
# importance matrix
imp.mat <- xgb.importance(model = xgboost.fit)
xgb.ggplt<-xgb.ggplot.importance(importance_matrix = imp.mat, top_n = 10)+ 
  ggtitle("XGBoost Feature Importance") 

# ROC curve plot 
roc.xgb <- roc.curve(testing$swing.miss, pred.xgb, main = "AUROC XGBoost: 0.778")
```

