---
title: "initialEDA"
author: "Emma Godfrey"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pitches <- read.csv("~/Downloads/pitches.csv")
```

```{r}
library("tidyverse")
library("tune")
library("randomForest")
library("ROCR")
library("ROSE")
library("ggplot2")
library("reshape2")
library("scatterplot3d")
```

```{r}
# only consider events where the batter swings at the ball
pitches <- pitches %>% 
  filter(is.na(pitches) == FALSE) %>% 
  filter(code %in% c("L", "T", "F", "X", "D", "E", "S", "W", "M")) %>% 
  mutate(swing.miss = ifelse(code == "S" & type == "S" | code == "W" & type == "S" | code == "M" & type == "S", 1, 0))

pitches$swing.miss <- as.factor(pitches$swing.miss)
```

```{r}
set.seed(100)
pitches$type <- as.factor(pitches$type)

pitches.samp <- pitches[sample(nrow(pitches),700, replace = FALSE),]

colors <- c("red", "blue", alpha = 0.2)
colors <- colors[as.numeric(pitches.samp$swing.miss)]
s3d <- scatterplot3d(x=pitches.samp$pfx_x, y=pitches.samp$pfx_z, z= pitches.samp$end_speed, pch= 10, color = colors, main = "Pitch speed and change in trajectory to predict swing contact", xlab = "Change in horizontal trajectory (pfx_x)", zlab = "End speed", ylab = "Change in vertical trajectory (pfx_z)")
legend(s3d$xyz.convert(10, -10,60), col= c("red", "blue"), bg="white", lty=c(1,1), lwd=2, yjust=0, legend = c("Swing & contact", "Swing & no contact"), cex = 0.5)

```


```{r}
p <- ggplot(data = pitches.samp, mapping = aes(x=pfx_x, y=pfx_z, color = swing.miss)) + 
  geom_point(aes(alpha = end_speed)) + labs(x="Change in Horizontal Trajectory (pfx_x)", y="Change in Vertical Trajectory (pfx_z)", color = "Contact (0=yes, 1 =no)", alpha = "End Speed", title = "Will the batter make contact?", subtitle = "the change in horizontal/vertical trajectory and end speed of pitch affecting contact likelihood") + 
  theme_minimal() +theme(plot.title = element_text(face = "bold"))
```

fastball, changeup, curveball, slider

```{r}
pitches3 <- pitches %>% 
  filter(pitch_type == "CH" | pitch_type == "CU" | pitch_type == "SL" | pitch_type == "FF"| pitch_type == "FT")

ggplot(data=pitches3, aes(x=pitch_type, fill = swing.miss)) + 
  geom_bar() + 
  labs(x="Pitch Type", y="Contact vs. No Contact Count", fill = "Ball Contact (0=yes, 1 =no)", title = "Pitch Type and Contact") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))
```

```{r}
ggplot(data = pitches.samp, aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir))

pitches.samp.fastball <- pitches %>% 
  filter(pitch_type == "FF" | pitch_type == "FT")

pitches.samp.curveball <- pitches %>% 
  filter(pitch_type == "CU")

pitches.samp.change <- pitches %>% 
  filter(pitch_type == "CH")


fast <- ggplot(data = pitches.samp.fastball[1:500,], aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do fastball spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)")+ 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

curve <- ggplot(data = pitches.samp.curveball[1:500,], aes(color=swing.miss)) +
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do curveball spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

change <- ggplot(data = pitches.samp.change[1:500,], aes(color=swing.miss)) + 
  geom_point(aes(x=spin_rate, y = spin_dir)) + 
  labs(x = "Spin Rate (RPM)", y = "Spin Direction (degrees)", title = "Do changeup spin properties affect contact likelihood?",color = "Ball Contact (0=yes, 1 =no)") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")

ggplot(data=pitches3, aes(x=zone, fill = swing.miss)) + 
  geom_bar() + 
  labs(x="Zone", y="Contact vs. No Contact Count", fill = "Ball Contact (0=yes, 1=no)", title = "Zone and Contact") + 
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"), legend.position = "bottom")
```

```{r}
set.seed(100)
pitches5 <- pitches[sample(nrow(pitches), 0.05*nrow(pitches), replace = FALSE),]
pitches5$type <- as.factor(pitches5$type)
```


```{r training and testing}
set.seed(100)
train.samp <- sample(nrow(pitches5), 0.7*nrow(pitches5), replace= FALSE)
training <- pitches5[train.samp,-c(28, 29,31,32,33,34,35,36,37,38,39,40)]
testing <- pitches5[-train.samp,-c(28, 29,31,32,33,34,35,36,37,38,39,40)]
```

```{r random forest}
# up-sampling
training.balanced <- ovun.sample(swing.miss~., data = training, method = "over")$data

# balanced dataset 
table(training.balanced$swing.miss)

# random sample to build models on 
model.samp <- sample(nrow(training.balanced), 0.5*nrow(training.balanced), replace=FALSE)
training.build.model <- training.balanced[model.samp,]
training.build.model$zone <- as.factor(trainig.build.model$zone)
training.build.model$pitch_type <- as.factor(trainig.build.model$pitch_type)
training.build.model$nasty <- as.numeric(training.build.model$nasty)

# tune mtry -- # of variables randomly chosen to split on at each tree
rf.tune <- tuneRF(training.build.model[,-29], training.balanced[,29], ntreeTry = 50, verbose=TRUE)

rf1 <- randomForest(swing.miss ~ ., data = training.balanced[], ntree=200, mtry=3, do.trace = 100)

# testing data predictions 
predictions <- predict(rf1, newdata = testing[,-39],type="prob") 
testing.labels <- as.numeric(as.character(testing[,30]))

pred <- prediction(predictions[,2], testing[,39])

library("ROCR")
table(observed = testing[,30], predicted = predictions)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf, col="blue", main= "Random Forest Performance (AUROC = 0.765)")

# AUC -- 0.7646
auc.perf <- performance(pred, measure = "auc")
print(auc.perf@y.values)

# importance plot 
var.imp1 <- data.frame(importance(rf1, type=2))
var.imp1$Variables <- row.names(var.imp1)
varimp1 <- var.imp1[order(var.imp1$MeanDecreaseGini,decreasing = T),]
par(mar=c(10,5,1,1)) 
giniplot <- barplot(t(varimp1[-2]/sum(varimp1[-2])),las=2,
                     cex.names=1,
                    main="Gini Impurity Index Plot")

varImpPlot(rf1, n.var =10, main ="Random Forest Variable Importance")
# visualization of predictions

plot.learner <- function(fit, x1LB, x1UB, x2LB, x2UB, data) {
#Plots preimage of linear decision boundary generated in 3 space by added basis function
#Inputs
# fit: svm object
# x1LB, x1UB: lower and upper bounds for variable x1
# x2LB, x2UB: lower and upper bounds for variable x2
# data: data frame containing variables, need to have variables named y, x1 and x2
x1.grid <- seq(x1LB, x1UB, length.out=100)
x2.grid <- seq(x2LB, x2UB, length.out=100)
data.pred <- c()
for (i in 1:length(x1.grid)) {
for (j in 1:length(x2.grid)) {
data.pred <- rbind(data.pred, c(x1.grid[i], x2.grid[j]))
}
}
data.pred <- as.data.frame(data.pred)
names(data.pred) <- c('x1', 'x2')
plot(data$x1,data$x2,col=as.numeric(data$y)+8)
points(data.pred[,1:2],col=as.numeric(predict(fit, newdata=data.pred))+2, cex=.2)
}

data.temp <- training.balanced
names(data.temp)[39] <- "y"
names(data.temp)[3] <- "x1"
names(data.temp)[5] <- "x2"
data.temp$y <- as.factor(data.temp$y)
data.temp1 <- data.temp[,c(3,5,39)]


plot.learner(rf1, min(data.temp$x1), max(data.temp$x1), min(data.temp$x2), max(data.temp$x2), data.temp1)
```


```{r neural networks}
# remove ordinal columns and scale data 
scaled <- apply(training.balanced[,-c(27, 28,39)], 2, scale)
scaled.joined <- data.frame(cbind(scaled, training.balanced[,c(27, 28,39)]))

scaled.joined.x <- as.matrix(scaled.joined[,-39])
scaled.joined.y <- as.matrix(scaled.joined[,39])
scaled.joined.clean <- scaled.joined[,-c(37,38)]


nn <- neuralnet(swing.miss ~ px + pz + start_speed + end_speed + spin_rate + spin_dir + break_angle + break_length, data = scaled.joined.clean[1:5000,], hidden=c(2,1), linear.output=FALSE, threshold=0.01)

nn$result.matrix
plot(nn)

pred.nn <- compute(nn, testing)
pred.nn
```

```{r}
library("e1071")
tune_out <- tune.svm(swing.miss ~., data = training.balanced[sample(nrow(training.balanced), 0.5*nrow(training.balanced), replace =FALSE),],gamma = 2^c(-8,-4,0,4), cost = 2^c(-8,-4,-2,0))

svmfit1 <- svm(swing.miss~., data = training.balanced[sample,], type = 'C-classification', verbose=TRUE)

sample <- sample(nrow(training.balanced), 0.1*nrow(training.balanced), replace=FALSE)

print(svmfit1)
princomp <- prcomp(training.balanced[,-c(28,29,39)])

training.balanced$nasty <- as.numeric(training.balanced$nasty)
training.balanced$zone <- as.numeric(training.balanced$zone)


pred.svm <- predict(svmfit1, training.balanced[,-c(39)])

plot(svm, mode="pca")

```

